const jirehPreset = {
  theme: {
    colors: {
      "jireh-purple": "var(--color-jireh-purple)",
      "jireh-purple-dark": "var(--color-jireh-purple-dark)",
      "jireh-green": "var(--color-jireh-green)",
      bubblegum: {
        DEFAULT: "var(--color-bubblegum)",
        light: "var(--color-bubblegum-light)",
        lightest: "var(--color-bubblegum-lightest)",
      },
      "bg-page": "var(--bg-page)",
      "bg-surface": "var(--bg-surface)",
      "bg-surface-raised": "var(--bg-surface-raised)",
      "bg-surface-muted": "var(--bg-surface-muted)",
      "bg-surface-brand": "var(--bg-surface-brand)",
      "bg-surface-brand-light": "var(--bg-surface-brand-light)",
      "fg-default": "var(--fg-default)",
      "fg-heading": "var(--fg-heading)",
      "fg-muted": "var(--fg-muted)",
      "fg-subtle": "var(--fg-subtle)",
      "fg-on-brand": "var(--fg-on-brand)",
      "fg-link": "var(--fg-link)",
      "border-default": "var(--border-default)",
      "border-strong": "var(--border-strong)",
      interactive: {
        DEFAULT: "var(--interactive-default)",
        hover: "var(--interactive-hover)",
        active: "var(--interactive-active)",
        disabled: "var(--interactive-disabled)",
      },
      success: { DEFAULT: "var(--color-success)", bg: "var(--color-success-bg)" },
      warning: { DEFAULT: "var(--color-warning)", bg: "var(--color-warning-bg)" },
      error: { DEFAULT: "var(--color-error)", bg: "var(--color-error-bg)" },
      info: { DEFAULT: "var(--color-info)", bg: "var(--color-info-bg)" },
    },
    fontFamily: {
      sans: "var(--font-sans)",
      mono: "var(--font-mono)",
    },
    borderRadius: {
      none: "var(--radius-none)",
      sm: "var(--radius-sm)",
      md: "var(--radius-md)",
      lg: "var(--radius-lg)",
      xl: "var(--radius-xl)",
      "2xl": "var(--radius-2xl)",
      full: "var(--radius-full)",
    },
    boxShadow: {
      none: "none",
      sm: "var(--shadow-sm)",
      md: "var(--shadow-md)",
      lg: "var(--shadow-lg)",
      xl: "var(--shadow-xl)",
    },
    zIndex: {
      base: "var(--z-base)",
      raised: "var(--z-raised)",
      dropdown: "var(--z-dropdown)",
      sticky: "var(--z-sticky)",
      overlay: "var(--z-overlay)",
      modal: "var(--z-modal)",
      toast: "var(--z-toast)",
      tooltip: "var(--z-tooltip)",
    },
    screens: {
      sm: "480px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1440px",
    },
    extend: {
      spacing: {
        "0.5": "var(--space-0-5)",
        "1": "var(--space-1)",
        "1.5": "var(--space-1-5)",
        "2": "var(--space-2)",
        "3": "var(--space-3)",
        "4": "var(--space-4)",
        "5": "var(--space-5)",
        "6": "var(--space-6)",
        "8": "var(--space-8)",
        "10": "var(--space-10)",
        "12": "var(--space-12)",
        "16": "var(--space-16)",
        "20": "var(--space-20)",
        "24": "var(--space-24)",
      },
      transitionDuration: {
        fast: "var(--duration-fast)",
        moderate: "var(--duration-moderate)",
        slow: "var(--duration-slow)",
      },
      transitionTimingFunction: {
        default: "var(--ease-default)",
        spring: "var(--ease-spring)",
      },
    },
  },
};

export default jirehPreset;
